CREATE TABLE IF NOT EXISTS marketing (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR(320) NOT NULL UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'SUBSCRIBED'
    CHECK (status IN ('SUBSCRIBED', 'UNSUBSCRIBED')),
  source VARCHAR(50) NOT NULL DEFAULT 'STOREFRONT_FOOTER',
  subscribed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unsubscribed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_marketing_status
  ON marketing (status, subscribed_at DESC);
